name: Deploy Manual

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Build
        run: echo "build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Teste
        run: echo "test"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Aprovação Manual
        uses: hmarr/auto-approve-action@v3
      - name: Deploy
        run: echo "deploy"
