name: Deploy Manual

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Build
        run: echo "build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Teste
        run: echo "test"

  approve:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Aguarde a aprovação manual
        run: echo "Aguardando aprovação..."
    outputs:
      approved: "true"

  deploy:
    runs-on: ubuntu-latest
    needs: approve
    steps:
      - name: Deploy
        run: echo "deploy"
