# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ main ]


  workflow_dispatch:


jobs:

  build:
   
    runs-on: ubuntu-latest

    steps:
      
      - name: Build
        run: echo "Build"


      - name: Test
        run: echo "Test"
        
      - name: Deploy
        run: echo "Deploy"
      
