# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ devsecops ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    
      - name: SAST
        run: |
          mkdir reports
          docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src/horusec horuszup/horusec-cli:latest horusec start -p /src/horusec -P $(pwd) -o='txt' -O=/src/horusec/reports/horusec_report.txt

      - name: Archive horusec report
        uses: actions/upload-artifact@v4
        with:
          name: horusec_report
          path: reports/horusec_report.sarif

 
