# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ devsecops ]
    
permissions:
  contents: read
  security-events: write
  issues: write

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-20.04
    steps:
      - name: 🛠️ Checkout do Código
        uses: actions/checkout@v3


     
      - name: 📥 Adicionar repositório do Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

      - name: 🔍 Listar versões disponíveis do Docker
        run: apt-cache madison docker-ce

      - name: 📦 Instalar Docker versão 22 manualmente
        run: |
          sudo apt-get install -y docker-ce=5:20.10.13~3-0~ubuntu-focal \
                                  docker-ce-cli=5:20.10.13~3-0~ubuntu-focal \
                                  containerd.io --allow-downgrades
          sudo apt-mark hold docker-ce docker-ce-cli containerd.io

      - name: 🏗️ Verificar versão final do Docker instalada
        run: docker --version

      - name: Horusec
        run: |
          mkdir reports
          docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src/horusec horuszup/horusec-cli:latest horusec start -p /src/horusec -P $(pwd) -o='sarif' -O=/src/horusec/reports/horusec_report.sarif


      - name: Archive horusec report
        uses: actions/upload-artifact@v4
        with:
          name: horusec_report
          path: reports/horusec_report.sarif 

      - name: Bug Tracking com Defect Dojo
        uses: michelleamesquita/defect-dojo-action@main
        with:
          url_base: "http://54.146.249.105:8080//api/v2/"
          username: "admin"
          source_url: "https://github.com/michelleamesquita/aula-devsecops"
          tool: "Horusec"
          file: "horusec_report.sarif"
          scan_type: "SARIF"
          product_name: "Meu Projeto"
          description: "Projeto de teste no DefectDojo"
          origin: "third-party"
          token: ${{ secrets.DEFECTDOJO_TOKEN }}
         


      
