# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ devsecops ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  security_scan:
    runs-on: ubuntu-20.04
    steps:
      - name: 🛠️ Checkout do Código
        uses: actions/checkout@v3


      - name: 🏗️ Verificar a versão do Docker instalada
        run: docker --version
        

      - name: 🔍 Executar Horusec com Docker
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd):/src/horusec \
            horuszup/horusec-cli:latest \
            horusec start -p /src/horusec \
            -P $(pwd) -o='sarif' -O=/src/horusec/reports/horusec_report.sarif

      - name: Archive horusec report
        uses: actions/upload-artifact@v4
        with:
          name: horusec_report
          path: reports/horusec_report.sarif

 
