# This is a basic workflow to help you get started with Actions

name: CI


on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  build:
   
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      

      # Runs a single command using the runners shell
      - name: Build
        run: echo "Build"

# Runs a single command using the runners shell
      - name: Test
        run: echo "Test"
        
 # Runs a single command using the runners shell
      - name: Deploy
        run: echo "Deploy"
      
